import os
from google import genai

MODEL = "gemini-3.6-flash"


def run_critic_agent(hypothesis_output, anomaly_output):
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    prompt = f"""
You are the Critic Agent in a multi-agent scientific investigation system.

Your job is to aggressively challenge the hypotheses generated by the
Hypothesis Agent.

You are NOT allowed to simply agree with the hypotheses.

Your goal is to identify:
- unsupported assumptions
- logical weaknesses
- contradictions with observations
- missing evidence
- alternative explanations
- tests that could falsify each hypothesis

CRITICAL RULES:

1. Critique EVERY hypothesis.
2. Treat even high-plausibility hypotheses as unproven.
3. Do not use the historical answer or outside knowledge.
4. Do not introduce new facts that are not contained in the supplied evidence.
5. Distinguish correlation from causation.
6. Do not declare a hypothesis proven.
7. For every hypothesis, identify at least one way it could be wrong.
8. Prefer falsifiable scientific tests over vague recommendations.
9. If the evidence is insufficient to distinguish hypotheses, explicitly say so.
10. Be especially careful about claims of new physics.

Return ONLY valid JSON in exactly this structure:

{{
  "critiques": [
    {{
      "hypothesis_id": "H1",
      "main_weaknesses": [],
      "unsupported_assumptions": [],
      "evidence_that_would_falsify": [],
      "alternative_explanation": "",
      "severity": "low|medium|high"
    }}
  ],
  "cross_hypothesis_comparison": [
    {{
      "hypothesis_id": "H1",
      "relative_strength": "",
      "main_reason": ""
    }}
  ],
  "critical_unknowns": [],
  "recommended_discriminating_tests": []
}}

ANOMALY AGENT OUTPUT:

{anomaly_output}

HYPOTHESIS AGENT OUTPUT:

{hypothesis_output}
"""

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt
    )

    return response.text


if __name__ == "__main__":
    import json
    from evidence_agent import run_evidence_agent
    from anomaly_agent import run_anomaly_agent
    from hypothesis_agent import run_hypothesis_agent

    with open("data/pioneer/blind_case.json", "r") as f:
        case = json.load(f)

    evidence = run_evidence_agent(case)
    anomaly = run_anomaly_agent(evidence)
    hypotheses = run_hypothesis_agent(anomaly)

    result = run_critic_agent(hypotheses, anomaly)

    print("\n===== CRITIC AGENT =====\n")
    print(result)
